version: "3"
services:
    metricsweb:
        container_name: metricsweb
        build: .
        ports:
        - 5000:5000
        depends_on:
        - influxdb
        volumes:
            - /mnt/docker/metabuild-failures/html:/app/load_dir
        environment:
            - TZ=America/Fort_Wayne
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        ports:
        - 3000:3000
        #user: "1000:1000"
        volumes:
            - /mnt/docker/metabuild-failures/grafana/data:/var/lib/grafana
    influxdb:
        container_name: influxdb
        image: influxdb:latest
        ports:
        - 8086:8086
        user: "1000:1000"
        env_file:
            - 'env.influxdb'
        environment:
            - TZ=America/Fort_Wayne
        volumes:
            - /mnt/docker/metabuild-failures/influxdb/data:/var/lib/influxdb
            
